### PR TITLE
Cyclic wrapping adapter

### PR DESCRIPTION
**Pull request by elihart**
Possible way to address https://github.com/airbnb/epoxy/issues/396 and https://github.com/airbnb/epoxy/issues/375

I haven't tested this yet, but it seems like something like this should work.

Anybody see any possible issues?

### CODE REVIEW

**Comment by mradzinski** [comment]
Checked the code and it looks fine. I don't see any possible issues and although I haven't tested the branch it looks like it should work as it is. I think I'll be able to test it this weekend, if I find anything weird I'll let you know @elihart

**Comment by elihart** [comment]
Great!

**Comment by mradzinski** [comment]
@elihart I tested this. So far so good, works as expected and nothing weird arose from my tests (didn't exactly conducted extensive ones, but tested regular use cases and they all seemed fine). Let me know if I can be of any other help.

**Comment by elihart** [comment]
@mradzinski Thanks a bunch for testing!

I have decided not to merge this and instead provide it as a gist with instructions in the wiki: https://github.com/airbnb/epoxy/wiki/Cyclic-Adapters

I don't feel good about supporting this officially when item changes won't work properly. The wiki should provide enough information for people to customize this to best suit their use cases.

**Comment by mradzinski** [comment]
> I don't feel good about supporting this officially when item changes won't work properly

And that @elihart is one of the tests I didn't conduct 😞, shame on me. But yes, I agree that the wiki should provide enough info. Also, I gave it a thought last weekend while I was testing this and sometimes keeping libraries doing one thing but doing that one thing right is the best approach one can take. I consider Epoxy to be one of those libraries that don't certainly need to have lots of preconfigured/premade use cases since it's extensible by nature and the things it does it does them right AF. 

Us as developers should give a thought or two about how to accomplish certain stuff. As an example, Epoxy doesn't have a `TypedEpoxyController` which allows for delayed builds, however that's easily accomplished by creating your own Typed Controller that allows for delayed builds just by extending from `EpoxyController` and checking the other Typed Controllers code.

Cheers and thanks as always for your hard work!

**Comment by bkulaksiz** [comment]
Hello @elihart 

If it is possible with EpoxyRecyclerView, I would like to make an endless automatic scrolling carousel, but I do not know how to do with epoxy. Is there are any suggestion to make it? I could not find any way to implement it.

Best regards.

**Comment by bkulaksiz** [comment]
Any suggestion?

**Comment by jrocharodrigues** [comment]
Hi,
Any guidance on how to use the cycle adapter with a carousel?

I've tried to do it by extending the Carousel class, overriding the setAdapter model, so it wraps the initial adapter inside the Cycle Adapter in the gist, but it doesn't work and crashes.
``` 
override fun setAdapter(adapter: Adapter<*>?) {
        super.setAdapter(CyclicAdapter(adapter))
    }
```

I've tried to fix the crashes but i was not able to make it work...





Thanks in advance

**Pull request closed without merging**
