### PR TITLE
Upgrade KotlinPoet 1.0.0

### PR DESCRIPTION
**Pull request by shaishavgandhi05**

### CODE REVIEW

**Comment by shaishavgandhi05** [comment]
Hmm looks like Paris is still using an older KotlinPoet and that's causing some conflicts. 😐

**Comment by elihart** [comment]
Thanks for looking into this, we could try to update to update Paris soon

**Comment by shaishavgandhi05** [comment]
I can try and update Paris to 1.0.0-RC3 also.

**Comment by elihart** [comment]
That would be awesome

**Comment by shaishavgandhi05** [comment]
Have updated the Paris one as well but haven't got a response there. If @elihart you could take a look at that one.

**Comment by elihart** [comment]
Sorry for the delay, I think it best if @ngsilverman does the review on that one, but I'll follow up to make sure it happens once everyone returns from holiday break in january.

**Comment by MatushkaRossiya** [comment]
KotlinPoet 1.0.1 has been released recently, maybe you can bump the version in this pull request before merging. :)

**Comment by elihart** [comment]
Great - thanks!

**Pull request merged**
