### PR TITLE
ModelGroupHolder to get the pool from parent RecyclerView

### PR DESCRIPTION
**Pull request by eboudrant**
Fix for #1094

This change remove `PoolReference` from `ModelGroupHolder`. Instead it just need a `RecyclerView.RecycledViewPool`. 

This new pool is passed in the constructor by the `EpoxyModelGroup` as it is the only place we have access to the parent `RecyclerView`.

`EpoxyModelGroup` will try to find a pool from the closest `RecyclerView` parent. If the group is not in a `RecyclerView` then it will use a local pool.

### CODE REVIEW

**Comment by eboudrant** [comment]
@elihart let me know what you think (or if there is a better way of doing it). I had to update the `EpoxyModelGroup` which I was not expecting at first, kind of required to grab the parent's view pool.

**Review by elihart — APPROVED** [review]
@eboudrant this looks reasonable given the constraints. I'm a _little_ wary of putting the view pool in the model group as an intermediary (since technically the model could be reused in a separate recyclerview), but see why you had to do it that way.

The only other approach I can think of involves modifying `EpoxyViewHolder` to take a reference to the parent in `BaseEpoxyAdapter#onCreateViewHolder` and then passing that parent on to `EpoxyModelWithHolder#createNewHolder` when the holder is first created in `bind` (and then nulling out the parent to be safe after bind?)

This is a larger change, but is potentially more explicit and cleaner. I don't feel too strongly one way or another though so I'll leave it up to you

**Comment by eboudrant** [comment]
> since technically the model could be reused in a separate recyclerview
Can you elaborate a bit on this? I though a model (`EpoxyModelGroup`) is built for one controller/recyclerview (via `buildModels`) and never re-used.

**Comment by elihart** [comment]
>  I though a model (EpoxyModelGroup) is built for one controller/recyclerview (via buildModels) and never re-used. 

That's not a requirement anywhere, and technically it could be reused for performance optimizations. I highly doubt anyone is doing that though, as the kotlin dsl pushes away from that approach.

The paging epoxy controller is one example that does cache and reuse models, but it doesn't generally reuse them across different recyclerviews (unless you happened to manually switch the controller to a different recyclerview)

**Comment by eboudrant** [comment]
Closing as a cleaner solution was implemented here #1097.

**Pull request closed without merging**
