### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MahmoudMabrok**
add some badges

### CODE REVIEW

**Review by elihart — COMMENTED** [review]
thanks for contributing. I'll take the license and contributors badges, but let's drop the hit count

**Comment by MahmoudMabrok** [comment]
@elihart 
should i remove it [HIT badge], or you will do that?

**Comment by elihart** [comment]
@MahmoudMabrok you can remove it

**Comment by MahmoudMabrok** [comment]
@elihart 
i have removed it

**Review by elihart — APPROVED** [review]
Thanks!

**Pull request merged**
