### PR TITLE
Fix processor to include attributes from super class models in other modules

### PR DESCRIPTION
**Pull request by elihart**
https://github.com/airbnb/epoxy/issues/67

### CODE REVIEW

**Comment by geralt-encore** [comment]
How common is that usecase? I am just interested how you come up with an understanding that it's a problem that needs to be addressed.
And do you think that introducing whole new module just to test one non-standard usecase is a good idea?

**Comment by elihart** [comment]
I'm sure it's pretty rare. However, our team recently switched to using Buck as a build system, and so we are splitting our app into many modules. That's the only reason I noticed.

We have a base model we use that adds some airbnb specific support, so this base class has an annotated field. I noticed that models that extend it in our new modules don't work properly because of the module setup.

Few people would probably have this issue, but it's an issue for our team.

**Comment by geralt-encore** [comment]
Thanks for the detailed response!
Just out of curiosity, are you using plain Buck or OkBuck? Is really worth it in comparison with Gradle? Sorry for offtopic.

**Comment by elihart** [comment]
No worries about the off topic, its fun to talk about.

We're using OkBuck. It made it much easier to switch. Uber did the same thing recently and made some improvements to OkBuck and we were able to talk with them and follow how they did it, which helped a lot.

For a large app it seems to be very worth it. Gradle incremental builds were 1.5 - 2 minutes for us, and cleans were 5-7. Plus incremental builds weren't always reliable so you'd have to clean often.

We didn't notice a huge speed increase with Buck right away since we were still a single module project, but once we started splitting features into modules you notice a large speed increase. A  module for a decent sized feature builds in 5-10 seconds. And if you change multiple modules they build in parallel.

Resource changes still trigger a whole AAPT build though, so changing an xml file in a module results in a 1.5 minute build or so.

Buck has recently been adding support for Kotlin which will be great in the future. Using something like Anko instead of xml would help to get around the slow AAPT processing.

There are other caveats, like we're still figuring out our testing setup with Buck, but overall it's been a fairly smooth switch and very nice. Most of the work is in splitting up the app into modules, which can be a huge pain at first.

Once you have many modules Android Studio runs very slowly - gradle just doesn't handle it well. We instead are switching to plain Intellij with the Android plugin. This handles the modules much better and is faster.

**Comment by geralt-encore** [comment]
Thanks for sharing! Very interesting experience =)

**Pull request merged**
