### PR TITLE
Update kotlin to 1.3.31

### PR DESCRIPTION
**Pull request by miga9**
Updating kotlin from 1.2.71 to the latest, 1.3.31.

### CODE REVIEW

**Comment by elihart** [comment]
Thanks for doing this, but it is failing with
```
e: error: Epoxy Processor Exception:  Caused by BadClassFile: bad class file: /home/travis/build/airbnb/epoxy/epoxy-processor/build/libs/epoxy-processor-3.5.0.jar(com/airbnb/epoxy/KotlinUtilsKt$buildAnnotationSpecs$1.class)
    bad enclosing method attribute for class com.airbnb.epoxy.KotlinUtilsKt$buildAnnotationSpecs$1
    Please remove or make sure it appears in the correct subdirectory of the classpath.       Stacktrace:      com.airbnb.epoxy.ConfigManager.processConfigurations(ConfigManager.java:90)       com.airbnb.epoxy.EpoxyProcessor.processRound(EpoxyProcessor.java:185)       com.airbnb.epoxy.EpoxyProcessor.process(EpoxyProcessor.java:165)
```

Not sure why this is happening, but if you can fix it that would be fantastic :)

**Comment by miga9** [comment]
@elihart I was able to get it to work after a couple changes. 

1: Removed the default function parameters. I don't understand how this causes the bad class file issue. Would be curious to hear some theories/ideas if any.

2: Replaced the usages of experimental coroutines in anko with the stable coroutines. It was throwing the error: `java.lang.IllegalStateException: Backend Internal error: Exception during code generation`

**Comment by elihart** [comment]
Oh great! really appreciate you fixing that up - I have no idea why the default param values are causing problems, but nice work figuring it out. Also nice to have coroutines updated :)

**Comment by josephyanks** [comment]
@elihart The kotlin upgrade is a blocker for us upgrading, would it be possible to do a minor release to 3.5.1 so we can use an official version?

**Comment by elihart** [comment]
@josephyanks sure, I just pushed a 3.5.1 version with the change - it should be available in a few minutes

**Comment by josephyanks** [comment]
Thank you!

**Comment by miga9** [comment]
@elihart Thank you for addressing this so quickly!

**Pull request merged**
